kind = "DojoModel"
class_hash = "0x52442a1e8004abfb4b8a7592823e0571035b244825f50a4680429f527bafcdf"
original_class_hash = "0x52442a1e8004abfb4b8a7592823e0571035b244825f50a4680429f527bafcdf"
abi = "manifests/dev/base/abis/models/tournament-TournamentEntryModel-278948ec.json"
tag = "tournament-TournamentEntryModel"
qualified_path = "tournament::ls15_components::tournament::tournament_entry_model"
manifest_name = "tournament-TournamentEntryModel-278948ec"

[[members]]
name = "tournament_id"
type = "u64"
key = true

[[members]]
name = "game_id"
type = "u64"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false

[[members]]
name = "status"
type = "EntryStatus"
key = false
