kind = "DojoModel"
class_hash = "0x2c66dc06675adfbe14c97fe74f6b49a820a1f587088a9692b537f58f57a2245"
original_class_hash = "0x2c66dc06675adfbe14c97fe74f6b49a820a1f587088a9692b537f58f57a2245"
abi = "manifests/dev/base/abis/models/tournament-TournamentContracts-3cef2d44.json"
tag = "tournament-TournamentContracts"
qualified_path = "tournament::ls15_components::tournament::tournament_contracts"
manifest_name = "tournament-TournamentContracts-3cef2d44"

[[members]]
name = "contract"
type = "ContractAddress"
key = true

[[members]]
name = "eth"
type = "ContractAddress"
key = false

[[members]]
name = "lords"
type = "ContractAddress"
key = false

[[members]]
name = "loot_survivor"
type = "ContractAddress"
key = false

[[members]]
name = "oracle"
type = "ContractAddress"
key = false
