kind = "DojoModel"
class_hash = "0x3e24a849a95fb9c09e3c3b7c9d57a1b75ebcd22b5667b17118cdf631b24f8c5"
original_class_hash = "0x3e24a849a95fb9c09e3c3b7c9d57a1b75ebcd22b5667b17118cdf631b24f8c5"
abi = "manifests/dev/base/abis/models/tournament-TournamentEntriesModel-787b5199.json"
tag = "tournament-TournamentEntriesModel"
qualified_path = "tournament::ls15_components::tournament::tournament_entries_model"
manifest_name = "tournament-TournamentEntriesModel-787b5199"

[[members]]
name = "tournament_id"
type = "u64"
key = true

[[members]]
name = "game_ids"
type = "Array<u64>"
key = false
