kind = "DojoModel"
class_hash = "0x75ce6bccb35e6ffbc2fb79ea72f9d138974b1fd0277093e80cbbd98a35088f3"
original_class_hash = "0x75ce6bccb35e6ffbc2fb79ea72f9d138974b1fd0277093e80cbbd98a35088f3"
abi = "manifests/dev/base/abis/models/tournament-TournamentEntriesAddressModel-71659e89.json"
tag = "tournament-TournamentEntriesAddressModel"
qualified_path = "tournament::ls15_components::tournament::tournament_entries_address_model"
manifest_name = "tournament-TournamentEntriesAddressModel-71659e89"

[[members]]
name = "tournament_id"
type = "u64"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "entry_count"
type = "u8"
key = false

[[members]]
name = "game_ids"
type = "Array<u128>"
key = false
