kind = "DojoModel"
class_hash = "0x82049976c51a8a54a2d5a1e9b4bf20034bcaf3f96a9fd8155596b6c8693024"
original_class_hash = "0x82049976c51a8a54a2d5a1e9b4bf20034bcaf3f96a9fd8155596b6c8693024"
abi = "manifests/dev/base/abis/models/tournament-TournamentEntryModel-278948ec.json"
tag = "tournament-TournamentEntryModel"
qualified_path = "tournament::ls15_components::tournament::tournament_entry_model"
manifest_name = "tournament-TournamentEntryModel-278948ec"

[[members]]
name = "tournament_id"
type = "u64"
key = true

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false

[[members]]
name = "status"
type = "EntryStatus"
key = false
