kind = "DojoModel"
class_hash = "0xe2e162c4ccfd49726a936c070e21a8df9d8b52fe2d42e75edb3e136f27ae70"
original_class_hash = "0xe2e162c4ccfd49726a936c070e21a8df9d8b52fe2d42e75edb3e136f27ae70"
abi = "manifests/dev/base/abis/models/tournament-TokenModel-7f2b49a0.json"
tag = "tournament-TokenModel"
qualified_path = "tournament::ls15_components::tournament::token_model"
manifest_name = "tournament-TokenModel-7f2b49a0"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "symbol"
type = "ByteArray"
key = false

[[members]]
name = "token_type"
type = "TokenType"
key = false

[[members]]
name = "is_registered"
type = "bool"
key = false
