kind = "DojoModel"
class_hash = "0xd7dfe292af5867169fcf64a107b0870cf04792ea6e9d5f5927c27789996a37"
original_class_hash = "0xd7dfe292af5867169fcf64a107b0870cf04792ea6e9d5f5927c27789996a37"
abi = "manifests/dev/base/abis/models/tournament-TournamentModel-45244913.json"
tag = "tournament-TournamentModel"
qualified_path = "tournament::ls15_components::tournament::tournament_model"
manifest_name = "tournament-TournamentModel-45244913"

[[members]]
name = "tournament_id"
type = "u64"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "creator"
type = "ContractAddress"
key = false

[[members]]
name = "gated_token"
type = "Option<GatedToken>"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false

[[members]]
name = "end_time"
type = "u64"
key = false

[[members]]
name = "submission_period"
type = "u64"
key = false

[[members]]
name = "leaderboard_size"
type = "u8"
key = false

[[members]]
name = "entry_premium"
type = "Option<Premium>"
key = false

[[members]]
name = "prizes"
type = "Array<PrizeType>"
key = false

[[members]]
name = "stat_requirements"
type = "Array<StatRequirement>"
key = false

[[members]]
name = "claimed"
type = "bool"
key = false
