kind = "DojoModel"
class_hash = "0x115f37ecd16c111653401c4f343f71e795e918056ed4726488bb04459fa5236"
original_class_hash = "0x115f37ecd16c111653401c4f343f71e795e918056ed4726488bb04459fa5236"
abi = "manifests/dev/base/abis/models/tournament-BagModel-4ecead3a.json"
tag = "tournament-BagModel"
qualified_path = "tournament::ls15_components::loot_survivor::bag_model"
manifest_name = "tournament-BagModel-4ecead3a"

[[members]]
name = "adventurer_id"
type = "felt252"
key = true

[[members]]
name = "bag"
type = "Bag"
key = false
