kind = "DojoModel"
class_hash = "0x68523cf5d97398babd595bbb3950b993f10bfc5ad6705848c0955b845e21ea3"
original_class_hash = "0x68523cf5d97398babd595bbb3950b993f10bfc5ad6705848c0955b845e21ea3"
abi = "manifests/dev/base/abis/models/tournament-TournamentTotalModel-4d67de8d.json"
tag = "tournament-TournamentTotalModel"
qualified_path = "tournament::ls15_components::tournament::tournament_total_model"
manifest_name = "tournament-TournamentTotalModel-4d67de8d"

[[members]]
name = "contract"
type = "ContractAddress"
key = true

[[members]]
name = "total_tournaments"
type = "u64"
key = false
