kind = "DojoModel"
class_hash = "0x72c6666cfeebc41544f502cfe9c32ad7b91fce12881709420335794dfcb324a"
original_class_hash = "0x72c6666cfeebc41544f502cfe9c32ad7b91fce12881709420335794dfcb324a"
abi = "manifests/dev/base/abis/models/dojo_starter-DirectionsAvailable-77844f1f.json"
tag = "dojo_starter-DirectionsAvailable"
qualified_path = "dojo_starter::models::directions_available"
manifest_name = "dojo_starter-DirectionsAvailable-77844f1f"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
