kind = "DojoModel"
class_hash = "0x2e06be7cf406eb3161fedf460a47faca68855eb9dad7d505c1b1f1875192ccd"
original_class_hash = "0x2e06be7cf406eb3161fedf460a47faca68855eb9dad7d505c1b1f1875192ccd"
abi = "manifests/dev/base/abis/models/dojo_starter-Moved-504403e5.json"
tag = "dojo_starter-Moved"
qualified_path = "dojo_starter::systems::actions::actions::moved"
manifest_name = "dojo_starter-Moved-504403e5"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
