[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
address = "0x2c2a3597995ac41d3e6403495a39e8c76725ad7dcbb6621aef44de19b84c4fb"
transaction_hash = "0x5891ad9cfcaaf9a21cf2096b1f4952d83a69c39b9faf0a6b24935c0bd32444c"
block_number = 3
seed = "ls"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x4861487b5a2c1fad2559e88ad1fa7e9a278ed5718adac7fdc89c7a716685d63"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x24c141e6921888dc0cd7b524632df46e23f11383f4263190d37dd400afafed9"
class_hash = "0x72f996d58baa2474194b5646fec8f06a54550bd3db9d6fb23298b55c586d3a8"
abi = "abis/deployments/KATANA/contracts/client.json"
reads = []
writes = []
computed = []
name = "ls::systems::client::client"

[[models]]
kind = "DojoModel"
class_hash = "0x592277281102655eeda977f03b457823f25b253eb00ad11992a9392056c86ca"
name = "ls::models::client::client"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "game_id"
type = "felt252"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "url"
type = "felt252"
key = false

[[models.members]]
name = "rating"
type = "u8"
key = false

[[models.members]]
name = "player_address"
type = "felt252"
key = true

[[models.members]]
name = "play_count"
type = "felt252"
key = false

[[models.members]]
name = "vote_count"
type = "felt252"
key = false
