[world]
name = "Tournament"
description = "Tournament component"
website = "https://github.com/Provable-Games"
seed = "tournament"

[world.socials]
x = "https://x.com/provablegames"
github = "https://github.com/Provable-Games"

[namespace]
default = "tournament"

[env]
rpc_url = "http://localhost:5050/"
# world_address = "0x043b149fadbe95e3946fa124a9a6bd64ec5374b8765f2bb753289d520bd8546d"  # Uncomment and update this line with your world address.