kind = "DojoModel"
class_hash = "0x3b054b56a5136aa816fb56bf6005214b94e88d1f859ca69cdaa4a593f2b8b3a"
abi = "abis/base/models/config.json"
name = "ls::models::config::config"

[[members]]
name = "key"
type = "u8"
key = true

[[members]]
name = "reward_token_address"
type = "ContractAddress"
key = false
