[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0xc82dfe2cb4f8a90dba1e88dfa24578aeb1c19152d51e3c7cf413be6d65d9e"
transaction_hash = "0x739d9f727cfbbaa5a428196fd7686bcc2f7be1e8af0c6e713526d00cdd11f41"
block_number = 3
seed = "dojo_starter"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x122ca6adae523511fbc9e13250b56ef98cebcb6914acfc5b4095f37d8699bc1"
class_hash = "0x31d69e598e30ac6cf1e090458ac3bddf7c1e181e2fbe74f32f4441d85860522"
original_class_hash = "0x31d69e598e30ac6cf1e090458ac3bddf7c1e181e2fbe74f32f4441d85860522"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_starter-actions-7a1c7102.json"
reads = []
writes = [
    "dojo_starter-Moves",
    "dojo_starter-Position",
    "dojo_starter-DirectionsAvailable",
]
init_calldata = []
tag = "dojo_starter-actions"
systems = [
    "spawn",
    "move",
]
manifest_name = "dojo_starter-actions-7a1c7102"

[[models]]
kind = "DojoModel"
class_hash = "0x72c6666cfeebc41544f502cfe9c32ad7b91fce12881709420335794dfcb324a"
original_class_hash = "0x72c6666cfeebc41544f502cfe9c32ad7b91fce12881709420335794dfcb324a"
abi = "manifests/dev/deployment/abis/models/dojo_starter-DirectionsAvailable-77844f1f.json"
tag = "dojo_starter-DirectionsAvailable"
qualified_path = "dojo_starter::models::directions_available"
manifest_name = "dojo_starter-DirectionsAvailable-77844f1f"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "directions"
type = "Array<Direction>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2e06be7cf406eb3161fedf460a47faca68855eb9dad7d505c1b1f1875192ccd"
original_class_hash = "0x2e06be7cf406eb3161fedf460a47faca68855eb9dad7d505c1b1f1875192ccd"
abi = "manifests/dev/deployment/abis/models/dojo_starter-Moved-504403e5.json"
tag = "dojo_starter-Moved"
qualified_path = "dojo_starter::systems::actions::actions::moved"
manifest_name = "dojo_starter-Moved-504403e5"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4eac0db062821cc05485ba088b0bb748de83e901116216da171744dfc5ec6fa"
original_class_hash = "0x4eac0db062821cc05485ba088b0bb748de83e901116216da171744dfc5ec6fa"
abi = "manifests/dev/deployment/abis/models/dojo_starter-Moves-2a29373f.json"
tag = "dojo_starter-Moves"
qualified_path = "dojo_starter::models::moves"
manifest_name = "dojo_starter-Moves-2a29373f"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models.members]]
name = "can_move"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6531637b0bbd741f8823b127d8958ed10a483dd1f2d7654975c1d7d7cbdab65"
original_class_hash = "0x6531637b0bbd741f8823b127d8958ed10a483dd1f2d7654975c1d7d7cbdab65"
abi = "manifests/dev/deployment/abis/models/dojo_starter-Position-2ac8b4c1.json"
tag = "dojo_starter-Position"
qualified_path = "dojo_starter::models::position"
manifest_name = "dojo_starter-Position-2ac8b4c1"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
