kind = "DojoContract"
class_hash = "0x531eaabc4bdc392d62a4727a834f8be324952c7b24168626c6eede6364cdb7e"
original_class_hash = "0x531eaabc4bdc392d62a4727a834f8be324952c7b24168626c6eede6364cdb7e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tournament-tournament_mock-5d8d96cf.json"
reads = []
writes = []
init_calldata = []
tag = "tournament-tournament_mock"
systems = ["initializer"]
manifest_name = "tournament-tournament_mock-5d8d96cf"
