kind = "DojoContract"
class_hash = "0x764a3fc88941f9dd0545ab2ef047047e42fe598b2886c08a501c3bf856a8439"
original_class_hash = "0x764a3fc88941f9dd0545ab2ef047047e42fe598b2886c08a501c3bf856a8439"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tournament-loot_survivor_mock-33ee7e60.json"
reads = []
writes = []
init_calldata = []
tag = "tournament-loot_survivor_mock"
systems = ["initializer"]
manifest_name = "tournament-loot_survivor_mock-33ee7e60"
