kind = "DojoContract"
class_hash = "0x47bf1dedf0c15f72bc43ce1e45def8badb2b973a36e2f2c429214983b7ee3f"
original_class_hash = "0x47bf1dedf0c15f72bc43ce1e45def8badb2b973a36e2f2c429214983b7ee3f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tournament-pragma_mock-5890442e.json"
reads = []
writes = []
init_calldata = []
tag = "tournament-pragma_mock"
systems = []
manifest_name = "tournament-pragma_mock-5890442e"
